### ISSUE TITLE
Some suggestions to improve the theme

### ISSUE THREAD

**Issue by newincpp** [Sythenz/UE4Minimal#1]
Hi,
I love this theme but I find some area where it could be improved fairly easily:
First the ColorSpill on variabled is beautifull but really thin so when I zoom out I just can't see the ColorSpill and therefore the type <img width="498" alt="Screenshot 2019-11-02 at 16 56 43" src="https://user-images.githubusercontent.com/3410903/68073961-027a4500-fd96-11e9-9e24-7fcda729e2c3.png">

Second the float sliders looks really blobby 
<img width="301" alt="Screenshot 2019-11-02 at 17 02 51" src="https://user-images.githubusercontent.com/3410903/68074030-b8de2a00-fd96-11e9-88c4-81cf57722287.png">

and Last: Shadows on squared dropdown look like make them look like win95-98: 
<img width="329" alt="Screenshot 2019-11-02 at 17 00 58" src="https://user-images.githubusercontent.com/3410903/68074049-0d81a500-fd97-11e9-9c8f-8e36781a1646.png"> I think that by making flat rounded buttons (much like the AddComponent button or the dropdowns for selecting assets) that would make the whole interface a bit more coherent and less aggressive.

I tried to modify those myself but it seems I'm not as good as you to do beautiful UI stuff.

**Comment by shaderwitch** [comment]
Thanks for the comment!

So on the **color spill,** specifically with regards to node headers (Just for some insight). I've already reported this to Epic but they had told me this _'works as intended.'_ There is basically a bug where only certain nodes actually use a colored background. In most cases this normally works fine as there is three layers; background, shadow, gloss - the latter of which I had removed - but the background color in Vanilla UE4 is basically hidden by the shadow.

This leads to the rather infuriating issue that I can't solve without a custom build of the engine, that the widget for the header of each node will sometimes have a default grey, and other times will work as intended.

More to the point of variables, which was your critique - I can potentially increase it by another pixel or two, and check it on zoom-out, but it's a good idea I hadn't thought of this issue. 

As for the bottom two - I completely agree! I need to come up with a much better 'dark button' motif that reads well when clicked and hovered. This will be my next update as soon as I can get around to UE4 Minimal again (apartment hunting right now).

I do really like the Add Component button motif, I think it's minimalism suits the editor, and indeed, UE4 Minimal quite well. If I can potentially replicate that, then I may just go with that.

I really appreciate the feedback, 
Sincerely yours, 
Alessa. <3

**Comment by shaderwitch** [comment]
Just a small update! Please check the latest commit - I've modified the buttons (dropdowns) to simplify the existing Vanilla UE4 button design, gradients remain only because buttons by design use gradients to differentiate between buttons/dropdowns and fields you can type in.

The button itself should hopefully feel cleaner, but I was unable to replicate the Add Component as I cannot change padding or text color and exceeds the limitations of this theme.

I'll close off this issue when I can get the 'bubble' sliders fixed, I just need to find out which graphic it actually is first xD

Hope this looks better!
Alessa. <3

**Comment by shaderwitch** [comment]
Cleaned up the blobby spinboxes! <3
